### ISSUE TITLE
Show precedence of a task

### ISSUE THREAD

**Issue by atomiomi** [atomiomi/task-manager#18]
Fill star icon according to the precedence. I think `StarPrecedence` component should be done that renders star and fills it according to `value` property. `value` property defines precedence of a task.

**Comment by Expandel** [comment]
StarPrecedence component will return star icon according to value property.

**Comment by atomiomi** [comment]
what does it mean? It returns separate icon for each precedence value?

**Comment by Expandel** [comment]
yes

**Comment by atomiomi** [comment]
Could you send me example of icon for some value?
